"""PRIMAL — the reliability and interoperability layer for AI agents.

A2A-native. MCP-bridged. Built around seven composable pillars:
Guardian, Conductor, Trajectory, Continuity, Verifier, Atlas, Harness.
"""

from __future__ import annotations

from primal_ai.atlas import (
    ArmState,
    Atlas,
    Bandit,
    BanditOutcome,
    BYOProvider,
    Cascade,
    CascadeResult,
    Provider,
    ProviderHealth,
    ProviderInfo,
    RoutingDecision,
    RoutingStatus,
    ThompsonBandit,
    UCB1Bandit,
    register_provider,
    register_selector,
    unregister_provider,
)
from primal_ai.conductor import (
    Agent,
    AgentCard,
    Capability,
    Conductor,
    DelegationResult,
    DelegationStatus,
    Event,
    EventBus,
    EventKind,
    Pipeline,
    PipelineStep,
    register_agent,
    unregister_agent,
)
from primal_ai.continuity import (
    Autolearn,
    BYOAutolearn,
    Continuity,
    ProfileField,
    UserProfile,
    register_autolearn,
)
from primal_ai.guardian import (
    AllOf,
    AllowList,
    AnyOf,
    BlockList,
    DollarCap,
    Guardian,
    PIIRedact,
    Policy,
    PolicyViolation,
    RateLimit,
    SchemaValidator,
)
from primal_ai.harness import (
    Harness,
    HealthCheck,
    HealthStatus,
    JobStatus,
    ScheduledJob,
    Scheduler,
    ToolInfo,
    ToolRegistry,
    register_tool,
    unregister_tool,
)
from primal_ai.trajectory import (
    Step,
    StepKind,
    Trajectory,
    TrajectoryStatus,
    set_default_store,
)
from primal_ai.verifier import (
    BYOLLMJudge,
    DomainVerifier,
    JSONSchemaVerifier,
    LLMJudge,
    RegexMatchVerifier,
    RuleBasedVerifier,
    Verdict,
    VerdictStatus,
    Verifier,
    VerifierLayer,
    register_verifier,
)

__version__ = "0.1.0"

__all__ = [
    "Agent",
    "AgentCard",
    "AllOf",
    "AllowList",
    "AnyOf",
    "ArmState",
    "Atlas",
    "Autolearn",
    "BYOAutolearn",
    "BYOLLMJudge",
    "BYOProvider",
    "Bandit",
    "BanditOutcome",
    "BlockList",
    "Capability",
    "Cascade",
    "CascadeResult",
    "Conductor",
    "Continuity",
    "DelegationResult",
    "DelegationStatus",
    "DollarCap",
    "DomainVerifier",
    "Event",
    "EventBus",
    "EventKind",
    "Guardian",
    "Harness",
    "HealthCheck",
    "HealthStatus",
    "JSONSchemaVerifier",
    "JobStatus",
    "LLMJudge",
    "PIIRedact",
    "Pipeline",
    "PipelineStep",
    "Policy",
    "PolicyViolation",
    "ProfileField",
    "Provider",
    "ProviderHealth",
    "ProviderInfo",
    "RateLimit",
    "RegexMatchVerifier",
    "RoutingDecision",
    "RoutingStatus",
    "RuleBasedVerifier",
    "ScheduledJob",
    "Scheduler",
    "SchemaValidator",
    "Step",
    "StepKind",
    "ThompsonBandit",
    "ToolInfo",
    "ToolRegistry",
    "Trajectory",
    "TrajectoryStatus",
    "UCB1Bandit",
    "UserProfile",
    "Verdict",
    "VerdictStatus",
    "Verifier",
    "VerifierLayer",
    "__version__",
    "register_agent",
    "register_autolearn",
    "register_provider",
    "register_selector",
    "register_tool",
    "register_verifier",
    "set_default_store",
    "unregister_agent",
    "unregister_provider",
    "unregister_tool",
]
